# These pictures were created by Rob Probin, Claire Probin and Emily Probin in 2010. 
# Copyright (c) 2010 Rob Probin, Claire Probin, Emily Probin
# Porting and Modifications by Rob Probin, 2024.

all_off_image = []


###########################################################################
# xmas
###########################################################################

bauble = [
"                        ",
"           WW           ",
"          W  W          ",
"           WW           ",
"          WWWW          ",
"        WW    WW        ",
"       WWW      W       ",
"      W   WWW    W      ",
"     WWW     WW   W     ",
"     W  WW     WW W     ",
"    WWWWWWWWWWWWWWWW    ",
"    W R R R R R R RW    ",
"    WR R R R R R R W    ",
"    WWWWWWWWWWWWWWWW    ",
"     WWW     WW   W     ",
"     W  WWW    WWWW     ",
"      W    WWW   W      ",
"       W      WWW       ",
"        WW    WW        ",
"          WWWW          ",
]

xmas_tree_inv_0 = [
"                        ",
"           W W          ",
"          W   W         ",
"           W W          ",
"          W   W         ",
"         W     W        ",
"        W       W       ",
"         W     W        ",
"        W       W       ",
"       W         W      ",
"      W           W     ",
"        W       W       ",
"       W         W      ",
"      W           W     ",
"     W             W    ",
"    W               W   ",
"           W W          ",
"           W W          ",
"         WWWWWWW        ",
"          WWWWW         ",
]

xmas_tree_inv_1 = [
"            W           ",
"           W W          ",
"          W   W         ",
"           W W          ",
"          W   W         ",
"         W   W W        ",
"        W       W       ",
"         W   W W        ",
"        W       W       ",
"       W    W    W      ",
"      W  W        W     ",
"        W       W       ",
"       W         W      ",
"      W  W        W     ",
"     W       W   W W    ",
"    W W             W   ",
"           W W          ",
"           W W          ",
"         WWWWWWW        ",
"          WWWWW         ",
]

xmas_tree_inv_2 = [
"                        ",
"           W W          ",
"          W   W         ",
"           W W          ",
"          WW  W         ",
"         W     W        ",
"        W W     W       ",
"         W     W        ",
"        W       W       ",
"       W       W W      ",
"      W  W        W     ",
"        W       W       ",
"       W    W  W W      ",
"      W           W     ",
"     W             W    ",
"    W               W   ",
"           W W          ",
"           W W          ",
"         WWWWWWW        ",
"          WWWWW         ",
]

xmas_tree_inv_4 = [
"            W           ",
"           W W          ",
"          W   W         ",
"           W W          ",
"          WW  W         ",
"         W   W W        ",
"        W W     W       ",
"         W   W W        ",
"        W       W       ",
"       W    W  W W      ",
"      W  W        W     ",
"        W       W       ",
"       W    W  W W      ",
"      W  W        W     ",
"     W       W   W W    ",
"    W W             W   ",
"           W W          ",
"           W W          ",
"         WWWWWWW        ",
"          WWWWW         ",
]

Holly = [
"                        ",
"                        ",
"                        ",
"                        ",
"   GGGG           GGGG  ",
"   GgGG           GGgG  ",
"   GGgGGGG     GGGggGG  ",
"   GGGggGG     GGGgGGG  ",
"     GGgGG     GGgGG    ",
"     GGggGGG GGGggGG    ",
"     GGGgggG GGggGGG    ",
"        GGgG GgGG       ",
"          Gg gGGG       ",
"        RR              ",
"       RR r RR          ",
"       RRrrRR r         ",
"        rr RRrr         ",
"            rr          ",
"                        ",
"                        ",
]

Holly_white = [
    "                        ", 
    "                        ",
    "                        ", 
    "                        ",
    "   WWWW           WWWW  ", 
    "   WWWW           WWWW  ",
    "   WWWWWWW     WWWWWWW  ", 
    "   WWWWWWW     WWWWWWW  ",
    "     WWWWW     WWWWW    ", 
    "     WWWWWWW WWWWWWW    ",
    "     WWWWWWW WWWWWWW    ", 
    "        WWWW WWWW       ",
    "          WW WWWW       ", 
    "        WW              ",
    "       WW W WW          ", 
    "       WWWWWW W         ",
    "        WW WWWW         ", 
    "            WW          ",
]
                                        
House_and_trees = [
"                      b ",
"            W        bbb",
"           W W     bbb  ",
"          W   W   bbb b ",
"         W     W        ",
"g       W       W RR    ",
"gg     W   Y Y   WRR   g",
"ggg   W           WR  gg",
"gg   W     Y Y     W  gg",
"ggg W               W gg",
"gggg               WWWgg",
"ggg   Y Y WWWWW Y Y  ggg",
"gggg      W W W       gg",
"ggggg Y Y W W W Y Y  ggg",
"ggg       W W W     gggg",
"gggg      W W W       gg",
"ggggg     WWWWW      ggg",
"gggggg    W W W     gggg",
"bb W      W W W    ggggg",
"bb W      WWWWW      W b",
]

Santa_in_his_sleigh = [
"                        ",
"                        ",
"  R   R  W              ",
"   R R    RR            ",
"   GGG   WWWW           ",
"  BGGG   WWWW           ",
" WBGGGO   WW            ",
" WWWWOOO RRRR           ",
" WR  WOO RRRRRW W       ",
" WR   WW RRRRRRW W      ",
" WR    WWWWWWWW  W      ",
" W R             W WW   ",
" W R             W   W  ",
"  W R            W    W ",
"   W R           W    W ",
"    WWWWWWWWWWWW      W ",
"     W   W    W       W ",
"     W   W    W      W  ",
"   WWWWWWWWWWWWWWWWWW   ",
"                        ",
]

Star = [
"                        ",
"                        ",
"           Y            ",
"           Y            ",
"          YYY           ",
"          YYY           ",
"         YYYYY          ",
"    YYYYYYYYYYYYYYY     ",
"     YYYYYYYYYYYYY      ",
"       YYYYYYYYY        ",
"        YYYYYYY         ",
"       YYYYYYYYY        ",
"       YYYY YYYY        ",
"      YYYY   YYYY       ",
"      YY       YY       ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

ho_ho_santa = [
"                        ",
" W W          WWWWW     ",
" WWW        WW     WW   ",
" W W      WWW        W  ",
"         W            W ",
"  W      W            W ",
" W W    W    WWWWWWW  W ",
" W W   WW  WW       WW  ",
"  W   WWWWWW  W   W  W  ",
"      WWWW            W ",
" W W   WW W WWWWWWWWW W ",
" WWW      WWWWWWWWWWWWW ",
" W W      WWWW     WWWW ",
"          WWWWW   WWWWW ",
"  W       WWWWWWWWWWWWW ",
" W W       WWWWWWWWWWW  ",
" W W       WWWWWWWWWWW  ",
"  W         WWWWWWWWW   ",
"              WWWWWW    ",
"                        ",
]

present = [
"                        ",
"       W        W       ",
"      W WW    WW W      ",
"      W   W  W   W      ",
"       WWWWWWWWWW       ",
"         WWWWWW         ",
"     WWWWWWWWWWWWWW     ",
"     W  WW WW WW  W     ",
"     W  WW WW WW  W     ",
"     W  W  WW  W  W     ",
"     W     WW     W     ",
"     WWWWWWWWWWWWWW     ",
"     WWWWWWWWWWWWWW     ",
"     W     WW     W     ",
"     W     WW     W     ",
"     W     WW     W     ",
"     W     WW     W     ",
"     W     WW     W     ",
"     WWWWWWWWWWWWWW     ",
"                        ",
]

happy_new_year = [
"W   W  WW  WWW WWW W   W",
"W   W W  W W W W W  W W ",
"WWWWW WWWW WWW WWW   W  ",
"W   W W  W W   W     W  ",
"W   W W  W W   W     W  ",
"                        ",
"                        ",
"   W   W WWWW W     W   ",
"   WW  W W    W     W   ",
"   W W W WWW   W W W    ",
"   W  WW W     W W W    ",
"   W   W WWWW   W W     ",
"                        ",
"                        ",
"  W   W WWWW  WW  WWW   ",
"   W W  W    W  W W  W  ",
"    W   WWW  WWWW WWW   ",
"    W   W    W  W W  W  ",
"    W   WWWW W  W W  W  ",
"                        ",
]

angel = [
"          WWWW          ",
"         W    W         ",
"          WWWW          ",
"                        ",
"           WW           ",
"          W  W          ",
"  WWW    W    W    WWW  ",
" W   W   W    W   W   W ",
" W    W   W  W   W    W ",
"W      W   WW   W      W",
"W       WWW  WWW       W",
"W       W W  W W       W",
"W      W  W  W  W      W",
"W     W  W    W  W     W",
"W    W   W    W   W    W",
"W   W    W    W    W   W",
"W   W   WWWWWWWW   W   W",
" W W      W  W      W W ",
"  W       W  W       W  ",
"         WW  WW         ",
]

gingerbread_man3 = [
"         WWWWWW         ",
"        WOOOOOOW        ",
"       WOOOOOOOOW       ",
"       WOOGOOGOOW       ",
"       WOOOOOOOOW       ",
"        WBOOOOBW         ",
"        WOBBBBOW       ",
"    WWWWOOOOOOOOWWWW    ",
"   WOOOOOOOOOOOOOOOOW   ",
"   WOOOOOOOPPOOOOOOOW   ",
"    WWOOOOOPPOOOOWW    ",
"       WOOOOOOOOW       ",
"       WOOOPPOOOW       ",
"       WOOOPPOOOW       ",
"      WOOOOOOOOOOW      ",
"     WOOOOOOOOOOOOW     ",
"    WOOOOOWWWWOOOOOW    ",
"   WOOOOWW    WWOOOOW   ",
"   WOOWW        WWOOW   ",
"    WW            WW    ",
]

rudolph = [
"      W W               ",
"    WWWWWW              ",
"      W W               ",
"      W W               ",
"   WWWWW                ",
"  W     W               ",
"WW  W    WWWWWW         ",
"WW             WWWW     ",
"  WWWW             WWWW ",
"      W            W   W",
"      W            W   W",
"      W            W    ",
"     W            W     ",
"    W  WWWWWWWWWWW      ",
"    W W      W   W      ",
"    W W      W   W      ",
"   W  W      W   W      ",
"   W W      W   W       ",
"   W W      W   W       ",
"  W  W      W   W       ",
]

rudolph2 = [
"   W    W               ",
"  WW   W                ",
" W W  WWW               ",
"   WWWW                 ",
"    WW                  ",
"   W  WWW               ",
"  W W    W              ",
"WW        WW           W",
"WW          WWWWWWWWWWWW",
"  WWWW                WW",
"      W               W ",
"       W              W ",
"       W              W ",
"   WWWWW              W ",
"  W   W       WWWWWW  W ",
" W   W  WWWWWWW  W W  W ",
"W  WW  W         W  W W ",
"W W  W W          W W  W",
" W   W  W         W  WW ",
"      WW           WWW  ",
]

ho_ho_santa_closed_mouth = [
"                        ",
" W W          WWWWW     ",
" WWW        WW     WW   ",
" W W      WWW        W  ",
"         W            W ",
"  W      W            W ",
" W W    W    WWWWWWW  W ",
" W W   WW  WW       WW  ",
"  W   WWWWWW  W   W  W  ",
"      WWWW            W ",
" W W   WW W WWWWWWWWW W ",
" WWW      WWWWWWWWWWWWW ",
" W W      WWWWW   WWWWW ",
"          WWWWWWWWWWWWW ",
"  W       WWWWWWWWWWWWW ",
" W W       WWWWWWWWWWW  ",
" W W       WWWWWWWWWWW  ",
"  W         WWWWWWWWW   ",
"              WWWWWW    ",
"                        ",
]

snowman2 = [
"                        ",
"                        ",
"          WWWW          ",
"         W    W         ",
"        W      W        ",
"       W  W  W  W       ",
"       W        W       ",
"       W   WW   W       ",
"  W     W   WW W        ",
"   W   W W    W W    WW ",
"  WWWWW   WWWW   WWWWW  ",
" W   W            W  WW ",
"     W     WW     W  W  ",
"     W     WW     W     ",
"     W            W     ",
"     W     WW     W     ",
"      W    WW    W      ",
"       W        W       ",
"        WW    WW        ",
"          WWWW          ",
]



xmas_list = [
  
    ( xmas_tree_inv_0, 5 ),
    ( xmas_tree_inv_1, 5 ),
    ( xmas_tree_inv_2, 5 ),
    ( xmas_tree_inv_4, 5 ),
    ( xmas_tree_inv_1, 5 ),
    ( xmas_tree_inv_2, 5 ),
    ( xmas_tree_inv_4, 5 ),
    ( xmas_tree_inv_1, 5 ),
    ( xmas_tree_inv_2, 5 ),
    ( xmas_tree_inv_4, 5 ),
    ( xmas_tree_inv_0, 5 ),
    
    ( all_off_image, 10 ),
    ( bauble, 20 ),
    
    ( Holly_white, 20 ), 
    ( Holly, 20 ),
    
    ( House_and_trees, 20 ),
    ( Santa_in_his_sleigh, 20 ),
    ( Star, 20 ),
    
    ( ho_ho_santa, 5 ),
    ( ho_ho_santa_closed_mouth, 5 ),
    ( ho_ho_santa, 5 ),
    ( ho_ho_santa_closed_mouth, 5 ),
    ( ho_ho_santa, 5 ),
    ( ho_ho_santa_closed_mouth, 5 ),
      
    # New pictures
    ( rudolph, 20 ),
    ( present, 20 ),
    ( happy_new_year, 20 ),
    ( angel, 20 ),
    ( gingerbread_man3, 20 ),
    ( rudolph2, 20 ),
    ( snowman2, 20 ),
    ( all_off_image, 10 ),
]

###########################################################################
# halloween
###########################################################################

emily_ghost = [
"         WWWWWWWWW      ",
"        WWWWWWWWWWW     ",
"        WWWWWWWWWWW     ",
"       WWWWWWWWWWWWW    ",
"       WWWWWWWW  WWW    ",
"      WWW  WWWW  WWWW   ",
"      WWW  WWWWWWWWWW   ",
"     WWWWWWWWWWWWWWWW   ",
"     WWWWWW WW WWWWWW   ",
"     WWWWWW WW WWWWWWW  ",
"     WWWWWWW  WWWWWWWW  ",
"      WWWWWWWWWWWWWWWW  ",
"      WWWWWWWWWWWWWWWWW ",
"      WWWWWWWWWWWWWWWWW ",
"      WWWWWWWWWWWWWWWWWW",
"      WWWWWWWWWWWWWWWWWW",
"      WWWWWWWWWWWWWWWWWW",
"     WWWWWWWWWWWWWWWWWWW",
"     WWW  WWWW  WW  WW W",
"     WW    WW   WW   W  ",
]

emily_pumpkin = [
"         WWW            ",
"         W W  WWWWWWW   ",
"       WWWWWWW       W  ",
"     WW               W ",
"    W                  W",
"   W          W        W",
"  W           W        W",
" W           WWW       W",
" W   W                 W",
" W   W                 W",
"W   WWW   W      W     W",
"W        WWW    WW    W ",
"W              WW    W  ",
"W      W     WWW    W   ",
" W     WWWWWWWW     W   ",
"  W     WWWWWW     W    ",
"   W              W     ",
"    W            W      ",
"     W         WW       ",
"      WWWWWWWWW         ",
]

emily_spider = [
"                        ",
"                      WW",
"                    WW  ",
"                   W    ",
"                  W     ",
"         WWWWWW  W      ",
"       WWWWWWWWWW    WWW",
"WWWWWWWWWW WW WWWWWWW   ",
"       WWWWWWWWWW       ",
"    WWWWWWWWWWWWW       ",
"WWWW   WWW WW WWWWWWWWWW",
"      WWWW WW WWW       ",
"   WWW WWWW  WWWW       ",
"WWW     WWWWWWWW WWWWWWW",
"      WW                ",
"    WW                  ",
"WWWW                    ",
"                        ",
"                        ",
"                        ",
]

skull = [
"      WWWWWWWWWWWWW     ",
"     WWWWWWWWWWWWWWW    ",
"    WWWWWWWWWWWWWWWWW   ",
"    WWWWWWWWWWWWWWWWW   ",
"    WWWW WWWWWWW WWWW   ",
"    WWW   WWWWW   WWW   ",
"    WW     WWW     WW   ",
"    WWW   WWWWW   WWW   ",
"    WWWW WWWWWWW WWWW   ",
"    WWWWWWW W WWWWWWW   ",
"     WWWWWW W WWWWWW    ",
"     WWWWWW W WWWWWW    ",
"      WWWWWWWWWWWWW     ",
"       WWWWWWWWWWW      ",
"       W WWWWWWW W      ",
"       W W W W W W      ",
"       W W W W W W      ",
"       WWW W W WWW      ",
"       WWWWWWWWWWW      ",
"        WWWWWWWWW       ",
]

pumpkin_eyes_1a = [
"  WW                  WW",
"  WWW                WWW",
"  WWWWW            WWWWW",
"  WWWWWWWW      WWWWWWWW",
"  WWWWW  WW    WWW  WWWW",
"  WWWWW  WW    WWW  WWWW",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

pumpkin_eyes_1b = [
"  WW                  WW",
"  WWW                WWW",
"  WWWWW            WWWWW",
"  WWWWWWWW      WWWWWWWW",
"  WWWW  WWW    WW  WWWWW",
"  WWWW  WWW    WW  WWWWW",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

pumpkin_eyes_1c = [
"  WW                  WW",
"  WWW                WWW",
"  WWWWW            WWWWW",
"  WWWWWWWW      WWWWWWWW",
"  WWW  WWWW    W  WWWWWW",
"  WWW  WWWW    W  WWWWWW",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

pumpkin_eyes_1d = [
"  WW                  WW",
"  WWW                WWW",
"  WWWWW            WWWWW",
"  WWWWWWWW      WWWWWWWW",
"  WWWWWW  W    WWWW  WWW",
"  WWWWWW  W    WWWW  WWW",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

face1 = [
"          WWWWWW        ",
"         WWWWWWWW       ",
"     WW WWWWWWWWWW WW   ",
"       WWWWWWWWWWWW     ",
"        WWWWWWWWWW      ",
"        WWWWWWWWWW      ",
"       WW   WW   WW     ",
"      WW W W  W W WW    ",
"     W WW   WW   WW W   ",
"     W  WWWW WWWWW  W   ",
"         WW WWWWW       ",
"        WWW WW WWW      ",
"       WW WW  WW WW     ",
"      W WW  WW  WW W    ",
"     W   WW    WW   W   ",
"          WWWWWW        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

face2 = [
"          WWWWWW        ",
"         WWWWWWWW       ",
"        WWWWWWWWWW      ",
"     WWWWWWWWWWWWWWWW   ",
"        WWWWWWWWWW      ",
"        WWWWWWWWWW      ",
"       WW   WW   WW     ",
"       W W W  W W W     ",
"      WWW   WW   WWW    ",
"     W  WWWW WWWWW  W   ",
"     W   WW WWWWW   W   ",
"        WWW WW WWW      ",
"       WW  W  W  WW     ",
"      W WW      WW W    ",
"      W  WW    WW  W    ",
"          WWWWWW        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

face3 = [
"          WWWWWW        ",
"         WWWWWWWW       ",
"        WWWWWWWWWW      ",
"     WW WWWWWWWWWW WW   ",
"       WWWWWWWWWWWW     ",
"        WWWWWWWWWW      ",
"       WW   WW   WW     ",
"       W W W  W W W     ",
"       WW    W   WW     ",
"      W WWW WWWWWW W    ",
"     W   WW WW WW   W   ",
"     W  WW W  W WW  W   ",
"        W  W  W  W      ",
"        WW      WW      ",
"       W WW    WW W     ",
"     WW   WWWWWW   WW   ",
"                        ",
"                        ",
"                        ",
"                        ",
]

face4 = [
"          WWWWWW        ",
"     W   WWWWWWWW   W   ",
"      W WWWWWWWWWW W    ",
"       WWWWWWWWWWWW     ",
"        WWWWWWWWWW      ",
"        W   WW   W      ",
"       W WWW  WWW W     ",
"       W W W  W W W     ",
"      WWW   WW   WWW    ",
"      W WWWW WWWWW W    ",
"     W   WW WWWWW   W   ",
"        WWW WW WWW      ",
"        W  W  W  W      ",
"      WWWW      WWWW    ",
"     W   WW    WW   W   ",
"          WWWWWW        ",
"                        ",
"                        ",
"                        ",
"                        ",
]

jsw_demon1 = [
"                        ",
"                        ",
"                        ",
"                        ",
"              W       W ",
"          W   W       W ",
"        W W W  W W W W  ",
"        W W W   WW WW   ",
"         WWW   W WW  W  ",
"          W   W WW WW W ",
"          WWW WW  W WWW ",
"          W  WW W W W  W",
"          W  W  WWWW   W",
"          W     WW WW WW",
"          W     W  WW   ",
"               W W W W  ",
"                        ",
"                        ",
"                        ",
"                        ",
]

jsw_demon2 = [
"                        ",
"                        ",
"                        ",
"                        ",
"              W       W ",
"              W       W ",
"               W WWW W  ",
"                WW WW   ",
"         W W   W W W W  ",
"         W W  W WWW W W ",
"          W   WW W WWWW ",
"        WWW  W WW W W  W",
"           WWWW WWWW   W",
"           WW   WW WW  W",
"            W   W  WW  W",
"            W  W W W W  ",
"             WW W   W W ",
"             W          ",
"                        ",
"                        ",
]

jsw_demon3 = [
"                        ",
"                        ",
"                        ",
"                        ",
"              W       W ",
"              WWW   WWW ",
"                WWWW    ",
"               W W W W  ",
"              W WW WW W ",
"              WWW WW WW ",
"           W   WW   W WW",
"         W  W W W W W  W",
"          W W WWWW WW WW",
"        W  W WW  WWWW   ",
"         WW WW  WW W    ",
"             W W W W W  ",
"              W W   W W ",
"               W        ",
"                W       ",
"                 W      ",
]

halloween_list = [
    ( emily_ghost , 20 ),
    ( emily_pumpkin , 20 ),
    ( emily_spider , 20 ),
    ( skull , 20 ),
    ( all_off_image , 5 ),
    
    ( pumpkin_eyes_1a , 5 ),
    ( pumpkin_eyes_1b , 5 ),
    ( pumpkin_eyes_1c , 5 ),
    ( pumpkin_eyes_1d , 5 ),
    ( pumpkin_eyes_1a , 5 ),
    ( pumpkin_eyes_1b , 5 ),
    ( pumpkin_eyes_1c , 5 ),
    ( pumpkin_eyes_1d , 5 ),
    ( pumpkin_eyes_1a , 5 ),
    ( pumpkin_eyes_1b , 5 ),
    ( pumpkin_eyes_1c , 5 ),
    ( pumpkin_eyes_1d , 5 ),
    ( all_off_image , 5 ),
    
    ( face1 , 5 ),
    ( face2 , 5 ),
    ( face3 , 5 ),
    ( face4 , 5 ),
    ( face1 , 5 ),
    ( face2 , 5 ),
    ( face3 , 5 ),
    ( face4 , 5 ),
    ( all_off_image , 5 ),
    
    ( jsw_demon1 , 5 ),
    ( jsw_demon2 , 5 ),
    ( jsw_demon3 , 5 ),
    ( jsw_demon1 , 5 ),
    ( jsw_demon2 , 5 ),
    ( jsw_demon3 , 5 ),
    ( all_off_image , 5 ),
]



